'use client';

import './ui/global.css';
import { geistSans, geistMono } from './ui/fonts';
import classNames from 'classnames';
import { useState } from 'react';
import Head from 'next/head';
import { AntdRegistry } from '@ant-design/nextjs-registry';
/*
export const metadata: Metadata = {
  title: "tommy's website",
  description: "Generated by create next app, i want to make something out of my own website",
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [bgClass, setBgClass] = useState(
    'bg-gradient-to-tr from-pink-500 via-red-500 to-yellow-500'
  );

  const colors = [
    'bg-gradient-to-tr from-pink-500 via-red-500 to-yellow-500',
    'bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500',
    'bg-gradient-to-r from-green-400 via-blue-500 to-purple-600',
    'bg-gradient-to-r from-yellow-400 via-orange-500 to-red-500',
    'bg-gradient-to-r from-teal-400 via-cyan-500 to-indigo-600',
    'bg-gradient-to-r from-pink-400 via-purple-500 to-indigo-600',
    'bg-gradient-to-r from-red-400 via-yellow-500 to-green-500',
  ];

  const handleClick = () => {
    const randomColor = colors[Math.floor(Math.random() * colors.length)];
    setBgClass(randomColor);
  };

  return (
    <html lang="en">
      <Head>
        <title>tommy&apos;s website</title>
        <meta
          name="description"
          content="Generated by create next app, I want to make something out of my own website"
        />
      </Head>
      <body
        className={classNames(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          bgClass
        )}
        onClick={handleClick}
      >
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}

/*        style={{ background: "linear-gradient(to right, #ff7e5f, #feb47b)"}}*/
